
spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-127.railway.app:7215/railway
    username: postgres
    password: 2rhx93klB4hP75D6eT1i
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: akbqkb780@gmail.com
    password: bauiubkecpadkhvy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000