server:
  port: 8080
  url: localhost:8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reddit_clone_db
    username: reddit_clone_user
    password: rootan
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: akbqkb780@gmail.com
    password: bauiubkecpadkhvy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

mail:
  reply:
    from: noreply@blahblah.com